import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const supabaseUrl = String.fromEnvironment('SUPABASE_URL');
const supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY');

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (supabaseUrl.isNotEmpty && supabaseAnonKey.isNotEmpty) {
    await Supabase.initialize(url: supabaseUrl, anonKey: supabaseAnonKey);
  }
  runApp(const App());
}

const wilayas = <String>['أدرار','الشلف','الأغواط','أم البواقي','باتنة','بجاية','بسكرة','بشار','البليدة','البويرة','تمنراست','تبسة','تلمسان','تيارت','تيزي وزو','الجزائر','الجلفة','جيجل','سطيف','سعيدة','سكيكدة','سيدي بلعباس','عنابة','قالمة','قسنطينة','المدية','مستغانم','المسيلة','معسكر','ورقلة','وهران','البيض','إليزي','برج بوعريريج','بومرداس','الطارف','تندوف','تيسمسيلت','الوادي','خنشلة','سوق أهراس','تيبازة','ميلة','عين الدفلى','النعامة','عين تموشنت','غرداية','غليزان','تيميمون','برج باجي مختار','أولاد جلال','بني عباس','عين صالح','عين قزام','تقرت','جانت','المغير','المنيعة','آفلو','بريكة','القنطرة','بئر العاتر','العريشة','قصر الشلالة','عين وسارة','مسعد','قصر البخاري','بوسعادة','الأبيض سيدي الشيخ'];

const professions = <String>['طبيب','طبيب أسنان','صيدلي','ممرض','أستاذ','محاسب','مدير','سكرتير','موظف استقبال','مسؤول مبيعات','مسوق','مصمم جرافيك','مصور','مبرمج','مطور تطبيقات','مطور مواقع','مهندس برمجيات','تقني إعلام آلي','محلل بيانات','مهندس مدني','مهندس معماري','مهندس كهرباء','مهندس ميكانيك','مهندس صناعي','كهربائي بناء','كهربائي صناعي','ميكانيكي سيارات','سباك','نجار','حداد','لحام','دهان','جباس','بلاط','عامل بناء','بنّاء','عامل ورشة','عامل مصنع','عامل إنتاج','عامل نظافة','حارس','عامل مخزن','خياط','حلاق','خباز','حلواني','طباخ','مساعد طباخ','نادل','بائع','تاجر','موزع','سائق سيارة','سائق شاحنة','سائق حافلة','سائق أجرة','سائق توصيل','فلاح','مزارع','مربي مواشي','مربي دواجن','مربي نحل','صياد','عامل بستان','عامل غراسة','عامل حصاد','تقني تبريد وتكييف','فني طاقة شمسية','فني كاميرات مراقبة','فني هواتف','صائغ','حرفي جلد','حرفي فخار','حرفي نحاس','مساعدة منزلية','مربية أطفال','مقدم رعاية كبار السن','موظف فندق','مرشد سياحي','موظف بنك','محامي','مستشار قانوني','أمن صناعي','مسؤول سلامة','باحث','مستقل Freelance','صاحب حرفة','صاحب مؤسسة','مهنة أخرى'];
const experiences = ['بدون خبرة','أقل من سنة','1 - 3 سنوات','3 - 5 سنوات','5 - 10 سنوات','أكثر من 10 سنوات'];
const ages = ['18 - 25 سنة','25 - 30 سنة','30 - 35 سنة','35 - 40 سنة','40 - 50 سنة','أكثر من 50 سنة'];
const genders = ['ذكر','أنثى','الكل'];
const workTypes = ['دوام كامل','دوام جزئي','مؤقت','يومي','موسمي','عن بُعد'];
const projectTypes = ['العقارات والبناء','الفلاحة وتربية المواشي','الصناعة والإنتاج','الصناعات الغذائية','التجارة والمحلات','النقل والخدمات اللوجستية','التكنولوجيا والبرمجيات','التطبيقات والمشاريع الرقمية','الصحة والعيادات','التعليم والتكوين','السياحة والفنادق','المطاعم والمقاهي','الطاقة والطاقة الشمسية','المياه','إعادة التدوير والبيئة','النسيج والملابس','السيارات وقطع الغيار','الورشات والحرف','الصيد وتربية الأسماك','الخدمات','مشاريع منزلية','مشاريع ناشئة','مشاريع صغيرة ومتوسطة','مشاريع صناعية كبرى','مشروع آخر'];
const investmentTypes = ['العقارات','الفلاحة','الصناعة','التجارة','الصناعات الغذائية','التكنولوجيا','الشركات الناشئة','التطبيقات والمنصات الرقمية','السياحة','الفنادق','المطاعم','النقل','الطاقة','الطاقة الشمسية','الصحة','التعليم','الخدمات','إعادة التدوير','السيارات وقطع الغيار','الصيد البحري','مشاريع صغيرة','مشاريع متوسطة','مشاريع كبيرة','شراء حصة في شركة','شراكة في مشروع قائم','تمويل مشروع جديد','استثمار آخر'];

class Invitation { String from,to,title,status; Invitation(this.from,this.to,this.title,{this.status='معلقة'}); }
class Job { String title,owner,wilaya,experience,age,gender,type; Job(this.title,this.owner,this.wilaya,this.experience,this.age,this.gender,this.type); }
class Project { String name,type,wilaya,amount,request,description; List<XFile> images; List<JobNeed> needs; Project(this.name,this.type,this.wilaya,this.amount,this.request,this.description,this.images,this.needs); }
class JobNeed { String profession,count,experience,age,gender,type; JobNeed(this.profession,this.count,this.experience,this.age,this.gender,this.type); }

class Data { static final invitations=<Invitation>[]; static final jobs=<Job>[Job('كهربائي بناء','مؤسسة البناء الحديث','سطيف','3 - 5 سنوات','25 - 40 سنة','ذكر','دوام كامل')]; static final projects=<Project>[]; }

class App extends StatelessWidget { const App({super.key}); @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'أرواح تخدم | مشاريع',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.green,scaffoldBackgroundColor:const Color(0xfff5f7f4)),home:const LoginPage()); }

class LoginPage extends StatefulWidget { const LoginPage({super.key}); @override State<LoginPage> createState()=>_LoginPageState(); }
class _LoginPageState extends State<LoginPage> { final p=TextEditingController(),pw=TextEditingController(); @override void dispose(){p.dispose();pw.dispose();super.dispose();} @override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.all(24),children:[const SizedBox(height:35),const CircleAvatar(radius:48,child:Icon(Icons.handshake,size:52)),const SizedBox(height:15),const Text('أرواح تخدم | مشاريع',textAlign:TextAlign.center,style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('منصة العمل والمشاريع والاستثمار',textAlign:TextAlign.center),const SizedBox(height:35),const Text('تسجيل الدخول',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:15),TextField(controller:p,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم الهاتف',prefixIcon:Icon(Icons.phone))),const SizedBox(height:12),TextField(controller:pw,obscureText:true,decoration:const InputDecoration(labelText:'كلمة المرور',prefixIcon:Icon(Icons.lock))),const SizedBox(height:20),SizedBox(height:52,child:FilledButton(onPressed:(){if(p.text.isEmpty||pw.text.isEmpty){snack(c,'أدخل رقم الهاتف وكلمة المرور');return;}Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const AccountPage()));},child:const Text('دخول'))),const SizedBox(height:12),OutlinedButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const RegisterPage())),child:const Text('ليس لديك حساب؟ إنشاء حساب جديد'))])))); }
}

class RegisterPage extends StatefulWidget { const RegisterPage({super.key}); @override State<RegisterPage> createState()=>_RegisterPageState(); }
class _RegisterPageState extends State<RegisterPage>{final p=TextEditingController(),pw=TextEditingController();@override void dispose(){p.dispose();pw.dispose();super.dispose();}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إنشاء حساب')),body:ListView(padding:const EdgeInsets.all(20),children:[TextField(controller:p,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم الهاتف')),const SizedBox(height:12),TextField(controller:pw,obscureText:true,decoration:const InputDecoration(labelText:'كلمة المرور')),const SizedBox(height:18),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const VerifyPage())),child:const Text('متابعة والتحقق من الهاتف'))])));}
}
class VerifyPage extends StatelessWidget{const VerifyPage({super.key});@override Widget build(BuildContext c){final x=TextEditingController();return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('التحقق من الهاتف')),body:ListView(padding:const EdgeInsets.all(20),children:[const Icon(Icons.verified_user,size:70,color:Colors.green),const SizedBox(height:15),const Text('أدخل رمز التحقق المرسل إلى هاتفك',textAlign:TextAlign.center),const SizedBox(height:15),TextField(controller:x,textAlign:TextAlign.center,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'رمز التحقق')),const SizedBox(height:15),FilledButton(onPressed:()=>Navigator.pushAndRemoveUntil(c,MaterialPageRoute(builder:(_)=>const AccountPage()),(_)=>false),child:const Text('تأكيد الحساب'))]));}}

class AccountPage extends StatelessWidget{const AccountPage({super.key});final types=const ['باحث عن عمل','صاحب عمل','شركة تبحث عن عمال','صاحب مشروع','مستثمر'];@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('اختر نوع الحساب')),body:ListView.separated(padding:const EdgeInsets.all(20),itemCount:types.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>Card(child:ListTile(title:Text(types[i],style:const TextStyle(fontWeight:FontWeight.bold)),leading:Icon([Icons.work,Icons.person_search,Icons.business,Icons.business_center,Icons.account_balance][i],color:Colors.green),trailing:const Icon(Icons.arrow_back_ios_new),onTap:()=>Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>HomePage(type:types[i]))))))));}
}

class HomePage extends StatelessWidget{final String type;const HomePage({super.key,required this.type});@override Widget build(BuildContext c){final items=[('أبحث عن عمل',Icons.work),('أبحث عن عامل',Icons.person_search),('الشركات تبحث عن عمال',Icons.business),('أبحث عن مشروع',Icons.business_center),('أبحث عن مستثمر',Icons.account_balance),('الدعوات',Icons.mail),('المحادثات',Icons.chat),('الإشعارات',Icons.notifications),('حسابي',Icons.person)];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('أرواح تخدم | مشاريع'),actions:[IconButton(onPressed:()=>go(c,'الدعوات',type),icon:Badge(isLabelVisible:Data.invitations.any((x)=>x.status=='معلقة'),child:const Icon(Icons.mail)))]),body:ListView(padding:const EdgeInsets.all(18),children:[Text('مرحبًا 👋',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),Text('نوع الحساب: $type',style:const TextStyle(color:Colors.grey)),const SizedBox(height:15),Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(borderRadius:BorderRadius.circular(20),gradient:const LinearGradient(colors:[Color(0xff064b3d),Color(0xff0b7259)])),child:const Text('فرص العمل • العمال • الشركات • المشاريع • الاستثمار',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.bold))),const SizedBox(height:15),...items.map((x)=>Card(child:ListTile(leading:Icon(x.$2,color:Colors.green),title:Text(x.$1),trailing:const Icon(Icons.arrow_back_ios_new,size:16),onTap:()=>go(c,x.$1,type))))]));}}

void go(BuildContext c,String t,String account){Widget p;switch(t){case 'أبحث عن عمل':p=const JobsPage();break;case 'أبحث عن عامل':p=const WorkersPage();break;case 'الشركات تبحث عن عمال':p=const CompanyPage();break;case 'أبحث عن مشروع':p=const ProjectsPage();break;case 'أبحث عن مستثمر':p=const InvestorPage();break;case 'الدعوات':p=const InvitationsPage();break;case 'المحادثات':p=const ChatsPage();break;case 'الإشعارات':p=const NotificationsPage();break;default:p=ProfilePage(account:account);}Navigator.push(c,MaterialPageRoute(builder:(_)=>p));}

class JobsPage extends StatefulWidget{const JobsPage({super.key});@override State<JobsPage> createState()=>_JobsPageState();}
class _JobsPageState extends State<JobsPage>{String? pr,w,e,a,g;@override Widget build(BuildContext c){final list=Data.jobs.where((j)=>(pr==null||j.title==pr)&&(w==null||j.wilaya==w)&&(e==null||j.experience==e)&&(g==null||g=='الكل'||j.gender==g)).toList();return page(c,'أبحث عن عمل',[Choice('المهنة',pr,professions,Icons.work,(v)=>setState(()=>pr=v)),Choice('الولاية',w,wilayas,Icons.location_on,(v)=>setState(()=>w=v)),Choice('سنوات الخبرة',e,experiences,Icons.star,(v)=>setState(()=>e=v)),Choice('السن',a,ages,Icons.cake,(v)=>setState(()=>a=v)),Choice('الجنس',g,genders,Icons.person,(v)=>setState(()=>g=v)),FilledButton.icon(onPressed:()=>setState((){}),icon:const Icon(Icons.search),label:const Text('بحث عن فرص العمل')),const SizedBox(height:15),Text('النتائج: ${list.length}',style:const TextStyle(fontWeight:FontWeight.bold)),...list.map((j)=>Card(child:ListTile(title:Text(j.title),subtitle:Text('${j.owner}\n📍 ${j.wilaya} • ⭐ ${j.experience} • 🎂 ${j.age} • ${j.gender}'),isThreeLine:true,trailing:FilledButton(onPressed:(){Data.invitations.add(Invitation('باحث عن عمل',j.owner,'دعوة بخصوص ${j.title}'));snack(c,'تم إرسال الدعوة');},child:const Text('دعوة'))))) ]);}}

class WorkersPage extends StatefulWidget{const WorkersPage({super.key});@override State<WorkersPage> createState()=>_WorkersPageState();}
class _WorkersPageState extends State<WorkersPage>{String? pr,w,e,a,g;final workers=const [['أحمد علي','كهربائي بناء','سطيف','3 - 5 سنوات','30 سنة','ذكر'],['محمد بوزيد','كهربائي بناء','سطيف','1 - 3 سنوات','28 سنة','ذكر'],['يوسف قاسمي','كهربائي بناء','وهران','3 - 5 سنوات','35 سنة','ذكر']];@override Widget build(BuildContext c){final list=workers.where((x)=>(pr==null||x[1]==pr)&&(w==null||x[2]==w)&&(e==null||x[3]==e)&&(g==null||g=='الكل'||x[5]==g)).toList();return page(c,'أبحث عن عامل',[Choice('الوظيفة / المهنة المطلوبة',pr,professions,Icons.work,(v)=>setState(()=>pr=v)),Choice('الولاية',w,wilayas,Icons.location_on,(v)=>setState(()=>w=v)),Choice('سنوات الخبرة المطلوبة',e,experiences,Icons.star,(v)=>setState(()=>e=v)),Choice('السن المطلوب',a,ages,Icons.cake,(v)=>setState(()=>a=v)),Choice('الجنس المطلوب',g,genders,Icons.person,(v)=>setState(()=>g=v)),FilledButton.icon(onPressed:()=>setState((){}),icon:const Icon(Icons.search),label:const Text('بحث عن عامل')),const SizedBox(height:15),...list.map((x)=>Card(child:ListTile(title:Text(x[0]),subtitle:Text('🔧 ${x[1]}\n📍 ${x[2]} • ⭐ ${x[3]} • 🎂 ${x[4]} • ${x[5]}'),isThreeLine:true,trailing:FilledButton(onPressed:(){Data.invitations.add(Invitation('صاحب عمل',x[0],'دعوة للعمل في ${x[1]}'));snack(c,'تم إرسال الدعوة للعامل');},child:const Text('دعوة'))))) ]);}}

class CompanyPage extends StatefulWidget{const CompanyPage({super.key});@override State<CompanyPage> createState()=>_CompanyPageState();}
class _CompanyPageState extends State<CompanyPage>{final company=TextEditingController();String? pr,w,e,a,g,t;final count=TextEditingController(text:'1');@override void dispose(){company.dispose();count.dispose();super.dispose();}@override Widget build(BuildContext c)=>page(c,'الشركات تبحث عن عمال',[TextField(controller:company,decoration:const InputDecoration(labelText:'اسم الشركة',prefixIcon:Icon(Icons.business))),Choice('المهنة المطلوبة',pr,professions,Icons.work,(v)=>setState(()=>pr=v)),Choice('الولاية',w,wilayas,Icons.location_on,(v)=>setState(()=>w=v)),Choice('الخبرة',e,experiences,Icons.star,(v)=>setState(()=>e=v)),Choice('السن',a,ages,Icons.cake,(v)=>setState(()=>a=v)),Choice('الجنس',g,genders,Icons.person,(v)=>setState(()=>g=v)),Choice('نوع العمل',t,workTypes,Icons.schedule,(v)=>setState(()=>t=v)),TextField(controller:count,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'عدد العمال المطلوبين')),const SizedBox(height:10),FilledButton.icon(onPressed:(){if(company.text.isEmpty||pr==null||w==null){snack(c,'أدخل اسم الشركة والمهنة والولاية');return;}Data.jobs.add(Job(pr!,company.text,w!,e??'بدون خبرة',a??'18 - 25 سنة',g??'الكل',t??'دوام كامل'));snack(c,'تم نشر إعلان الشركة');},icon:const Icon(Icons.publish),label:const Text('نشر إعلان التوظيف'))]);}
}

class ProjectsPage extends StatefulWidget{const ProjectsPage({super.key});@override State<ProjectsPage> createState()=>_ProjectsPageState();}
class _ProjectsPageState extends State<ProjectsPage>{String? type,w;@override Widget build(BuildContext c)=>page(c,'أبحث عن مشروع',[Choice('نوع المشروع',type,projectTypes,Icons.category,(v)=>setState(()=>type=v)),Choice('الولاية',w,wilayas,Icons.location_on,(v)=>setState(()=>w=v)),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const AddProjectPage())).then((_){setState((){});}),icon:const Icon(Icons.add),label:const Text('عرض مشروع جديد')),const SizedBox(height:10),...Data.projects.where((p)=>(type==null||p.type==type)&&(w==null||p.wilaya==w)).map((p)=>Card(child:ListTile(title:Text(p.name),subtitle:Text('${p.type}\n📍 ${p.wilaya}\n💰 ${p.amount}${p.needs.isNotEmpty?'\n👷 يحتاج عمال':''}'),isThreeLine:true,onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ProjectDetails(p))))))]);}}

class AddProjectPage extends StatefulWidget{const AddProjectPage({super.key});@override State<AddProjectPage> createState()=>_AddProjectPageState();}
class _AddProjectPageState extends State<AddProjectPage>{final name=TextEditingController(),amount=TextEditingController(),desc=TextEditingController();String? type,w,request;final imgs=<XFile>[];final needs=<JobNeed>[];@override void dispose(){name.dispose();amount.dispose();desc.dispose();super.dispose();}Future<void> photos()async{final x=await ImagePicker().pickMultiImage(imageQuality:80);if(x.isNotEmpty)setState(()=>imgs.addAll(x));}Future<void> addNeed()async{final n=await showModalBottomSheet<JobNeed>(context:context,isScrollControlled:true,builder:(_)=>const NeedSheet());if(n!=null)setState(()=>needs.add(n));}void publish(){if(name.text.isEmpty||type==null||w==null||amount.text.isEmpty){snack(context,'أدخل اسم المشروع والنوع والولاية والمبلغ');return;}Data.projects.add(Project(name.text,type!,w!,amount.text,request??'شراكة',desc.text,List.of(imgs),List.of(needs)));for(final n in needs){Data.jobs.add(Job(n.profession,name.text,w!,n.experience,n.age,n.gender,n.type));}snack(context,'تم نشر المشروع والوظائف المطلوبة');Navigator.pop(context);} @override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('عرض مشروع جديد')),body:ListView(padding:const EdgeInsets.all(18),children:[TextField(controller:name,decoration:const InputDecoration(labelText:'اسم المشروع')),Choice('نوع المشروع',type,projectTypes,Icons.category,(v)=>setState(()=>type=v)),Choice('الولاية',w,wilayas,Icons.location_on,(v)=>setState(()=>w=v)),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'المبلغ المطلوب للاستثمار')),Choice('نوع الطلب',request,['تمويل','شراكة','بيع المشروع'],Icons.handshake,(v)=>setState(()=>request=v)),TextField(controller:desc,maxLines:5,decoration:const InputDecoration(labelText:'وصف المشروع')),const SizedBox(height:10),OutlinedButton.icon(onPressed:photos,icon:const Icon(Icons.photo_library),label:Text('إضافة صور للمشروع (${imgs.length})')),if(imgs.isNotEmpty)SizedBox(height:90,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:imgs.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i)=>Image.file(File(imgs[i].path),width:100,fit:BoxFit.cover))),const SizedBox(height:15),Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('👷 هل مشروعك يحتاج إلى عمال؟',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const Text('الوظائف المضافة هنا تظهر أيضًا في أبحث عن عمل.'),FilledButton.icon(onPressed:addNeed,icon:const Icon(Icons.add),label:const Text('إضافة وظيفة مطلوبة')), ...needs.map((n)=>ListTile(title:Text(n.profession),subtitle:Text('${n.count} عامل • ${n.experience} • ${n.type}')))]))),const SizedBox(height:15),FilledButton.icon(onPressed:publish,icon:const Icon(Icons.publish),label:const Text('نشر المشروع'))])));}}

class NeedSheet extends StatefulWidget{const NeedSheet({super.key});@override State<NeedSheet> createState()=>_NeedSheetState();}
class _NeedSheetState extends State<NeedSheet>{String? p,e,a,g,t;final count=TextEditingController(text:'1');@override void dispose(){count.dispose();super.dispose();}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:SafeArea(child:Padding(padding:EdgeInsets.fromLTRB(18,18,18,18+MediaQuery.viewInsetsOf(c).bottom),child:ListView(shrinkWrap:true,children:[const Text('إضافة وظيفة مطلوبة',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),Choice('المهنة',p,professions,Icons.work,(v)=>setState(()=>p=v)),Choice('الخبرة',e,experiences,Icons.star,(v)=>setState(()=>e=v)),Choice('السن',a,ages,Icons.cake,(v)=>setState(()=>a=v)),Choice('الجنس',g,genders,Icons.person,(v)=>setState(()=>g=v)),Choice('نوع العمل',t,workTypes,Icons.schedule,(v)=>setState(()=>t=v)),TextField(controller:count,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'عدد العمال')),FilledButton(onPressed:(){if(p==null){snack(c,'اختر المهنة');return;}Navigator.pop(c,JobNeed(p!,count.text,e??'بدون خبرة',a??'18 - 25 سنة',g??'الكل',t??'دوام كامل'));},child:const Text('إضافة'))]))));}}

class InvestorPage extends StatelessWidget{const InvestorPage({super.key});@override Widget build(BuildContext c)=>page(c,'أبحث عن مستثمر',[Choice('مجال الاستثمار',null,investmentTypes,Icons.category,(_){ }),Choice('الولاية',null,wilayas,Icons.location_on,(_){ }),Choice('قيمة الاستثمار',null,['أقل من 5 ملايين دج','5 - 20 مليون دج','20 - 50 مليون دج','50 - 100 مليون دج','أكثر من 100 مليون دج'],Icons.payments,(_){ }),const Text('سيتم ربط المستثمرين الحقيقيين بالمشاريع بعد ربط قاعدة البيانات.')]);}}
class InvitationsPage extends StatefulWidget{const InvitationsPage({super.key});@override State<InvitationsPage> createState()=>_InvitationsPageState();}
class _InvitationsPageState extends State<InvitationsPage>{@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الدعوات')),body:Data.invitations.isEmpty?const Center(child:Text('لا توجد دعوات حاليًا')):ListView(padding:const EdgeInsets.all(18),children:Data.invitations.map((x)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(x.title,style:const TextStyle(fontWeight:FontWeight.bold)),Text('من: ${x.from}'),Text('إلى: ${x.to}'),Text('الحالة: ${x.status}'),if(x.status=='معلقة')Row(children:[Expanded(child:FilledButton(onPressed:(){setState(()=>x.status='مقبولة');snack(c,'تم قبول الدعوة، أصبح التواصل متاحًا');},child:const Text('قبول'))),const SizedBox(width:8),Expanded(child:OutlinedButton(onPressed:()=>setState(()=>x.status='مرفوضة'),child:const Text('رفض')))]),if(x.status=='مقبولة')FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ChatPage(name:x.to))),icon:const Icon(Icons.chat),label:const Text('فتح التواصل'))])))).toList())));}}
class ChatPage extends StatefulWidget{final String name;const ChatPage({super.key,required this.name});@override State<ChatPage> createState()=>_ChatPageState();}
class _ChatPageState extends State<ChatPage>{final x=TextEditingController();final msgs=<String>[];@override void dispose(){x.dispose();super.dispose();}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text('محادثة مع ${widget.name}')),body:Column(children:[Expanded(child:msgs.isEmpty?const Center(child:Text('تم قبول الدعوة. ابدأ التواصل.')):ListView(children:msgs.map((m)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Text(m)))).toList())),SafeArea(child:Row(children:[Expanded(child:TextField(controller:x,decoration:const InputDecoration(hintText:'اكتب رسالة...'))),IconButton.filled(onPressed:(){if(x.text.isNotEmpty)setState((){msgs.add(x.text);x.clear();});},icon:const Icon(Icons.send))]))]));}}
class ChatsPage extends StatelessWidget{const ChatsPage({super.key});@override Widget build(BuildContext c)=>const Center(child:Text('المحادثات التي فُتحت بعد قبول الدعوات ستظهر هنا.'));}
class NotificationsPage extends StatelessWidget{const NotificationsPage({super.key});@override Widget build(BuildContext c)=>const Center(child:Text('ستظهر هنا إشعارات الدعوات والوظائف والمشاريع.'));}
class ProfilePage extends StatelessWidget{final String account;const ProfilePage({super.key,required this.account});@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('حسابي')),body:ListView(padding:const EdgeInsets.all(20),children:[const CircleAvatar(radius:50,child:Icon(Icons.person,size:55)),const SizedBox(height:15),Center(child:Text('نوع الحساب: $account',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))),const Card(child:ListTile(leading:Icon(Icons.phone),title:Text('رقم الهاتف'))),const Card(child:ListTile(leading:Icon(Icons.location_on),title:Text('الولاية'),subtitle:Text('69 ولاية'))),const Card(child:ListTile(leading:Icon(Icons.work),title:Text('المهنة')))]));}}

class Choice{final String label;final String? value;final List<String> items;final IconData icon;final ValueChanged<String> on;Choice(this.label,this.value,this.items,this.icon,this.on);}
Widget page(BuildContext c,String title,List<dynamic> children)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(title)),body:ListView(padding:const EdgeInsets.all(18),children:[Text(title,style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const SizedBox(height:15),...children.map((x)=>x is Choice?ChoiceTile(x):Padding(padding:const EdgeInsets.only(bottom:10),child:x as Widget))])));
class ChoiceTile extends StatelessWidget{final Choice x;const ChoiceTile(this.x,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(leading:Icon(x.icon,color:Colors.green),title:Text(x.label),subtitle:Text(x.value??'اختر من القائمة'),trailing:const Icon(Icons.arrow_back_ios_new,size:16),onTap:()async{final v=await Navigator.push<String>(c,MaterialPageRoute(builder:(_)=>Picker(title:x.label,items:x.items)));if(v!=null)x.on(v);}));}
class Picker extends StatefulWidget{final String title;final List<String> items;const Picker({super.key,required this.title,required this.items});@override State<Picker> createState()=>_PickerState();}
class _PickerState extends State<Picker>{final q=TextEditingController();late List<String> list;@override void initState(){super.initState();list=widget.items;q.addListener(()=>setState(()=>list=widget.items.where((x)=>x.toLowerCase().contains(q.text.toLowerCase())).toList()));}@override void dispose(){q.dispose();super.dispose();}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(widget.title)),body:Column(children:[Padding(padding:const EdgeInsets.all(12),child:TextField(controller:q,decoration:const InputDecoration(hintText:'ابحث داخل القائمة',prefixIcon:Icon(Icons.search)))),Expanded(child:ListView(children:list.map((x)=>ListTile(title:Text(x),onTap:(){if(x=='مهنة أخرى'||x=='مشروع آخر'||x=='استثمار آخر'){final z=TextEditingController();showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('اكتب القيمة'),content:TextField(controller:z),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:(){final v=z.text.trim();Navigator.pop(c);if(v.isNotEmpty)Navigator.pop(c,v);},child:const Text('حفظ'))]));}else{Navigator.pop(c,x);}})).toList()))]));}}
class ProjectDetails extends StatelessWidget{final Project p;const ProjectDetails(this.p,{super.key});@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('تفاصيل المشروع')),body:ListView(padding:const EdgeInsets.all(18),children:[if(p.images.isNotEmpty)SizedBox(height:210,child:PageView(children:p.images.map((x)=>Image.file(File(x.path),fit:BoxFit.cover)).toList()))else Container(height:180,color:Colors.green.shade50,child:const Icon(Icons.business,size:80)),const SizedBox(height:15),Text(p.name,style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),Text('📌 ${p.type}'),Text('📍 ${p.wilaya}'),Text('💰 ${p.amount}'),Text('🤝 ${p.request}'),const SizedBox(height:15),Text(p.description.isEmpty?'لا يوجد وصف.':p.description),if(p.needs.isNotEmpty) ...[const SizedBox(height:18),const Text('الوظائف المطلوبة',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...p.needs.map((n)=>ListTile(title:Text(n.profession),subtitle:Text('${n.count} عامل • ${n.experience} • ${n.age} • ${n.gender}')))] ]));}}
void snack(BuildContext c,String s)=>ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(s)));
: 
