import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const url='https://xfftzmxcphvgpyhfbdto.supabase.co';
const key='sb_publishable_FaFRHnUm6QlmkPUoYyCKQA_-UcDd3g1';
final db=Supabase.instance.client;

Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); await Supabase.initialize(url:url,anonKey:key); runApp(const App()); }

class App extends StatelessWidget { const App({super.key}); @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'أرواح تخدم | مشاريع',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.green),home:const Gate()); }
class Gate extends StatelessWidget { const Gate({super.key}); @override Widget build(BuildContext c)=>db.auth.currentSession==null?const Login():const Home(); }

void toast(BuildContext c,String s)=>ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(s)));
String clean(Object e)=>e.toString().replaceFirst('Exception: ','');
InputDecoration deco(String s)=>InputDecoration(labelText:s,border:const OutlineInputBorder());
Widget dd(String label,String value,List<String> items,ValueChanged<String?> onChanged)=>Padding(padding:const EdgeInsets.only(bottom:10),child:DropdownButtonFormField<String>(initialValue:items.contains(value)?value:items.first,decoration:deco(label),items:items.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:onChanged));

const roles=['باحث عن عمل','صاحب عمل','شركة تبحث عن عمال','صاحب مشروع','مستثمر'];
String roleDb(String r)=>r=='باحث عن عمل'?'job_seeker':r=='مستثمر'?'investor':r=='صاحب مشروع'?'project_owner':'company';
const genders=['الكل','ذكر','أنثى'];
const categories=['فلاحة','تجارة','صناعة','سياحة','عقار','خدمات','تكنولوجيا','نقل','مطاعم','حرفي','طاقة','صحة','تعليم','أخرى'];
const requests=['partnership','sale','investment'];
final wilayas='''أدرار,الشلف,الأغواط,أم البواقي,باتنة,بجاية,بسكرة,بشار,البليدة,البويرة,تمنراست,تبسة,تلمسان,تيارت,تيزي وزو,الجزائر,الجلفة,جيجل,سطيف,سعيدة,سكيكدة,سيدي بلعباس,عنابة,قالمة,قسنطينة,المدية,مستغانم,المسيلة,معسكر,ورقلة,وهران,البيض,إليزي,برج بوعريريج,بومرداس,الطارف,تندوف,تيسمسيلت,الوادي,خنشلة,سوق أهراس,تيبازة,ميلة,عين الدفلى,النعامة,عين تموشنت,غليزان,تيميمون,برج باجي مختار,أولاد جلال,بني عباس,عين صالح,عين قزام,تقرت,جانت,المغير,المنيعة,آفلو,بريكة,القنطرة,بئر العاتر,العريشة,قصر الشلالة,عين وسارة,مسعد,قصر البخاري,بوسعادة,الأبيض سيدي الشيخ'''.split(',');

class Login extends StatefulWidget{const Login({super.key});@override State<Login> createState()=>_LoginState();}
class _LoginState extends State<Login>{final p=TextEditingController(),pw=TextEditingController();bool busy=false;Future<void> go()async{if(p.text.trim().isEmpty||pw.text.isEmpty)return toast(context,'أدخل الهاتف وكلمة المرور');setState(()=>busy=true);try{await db.auth.signInWithPassword(phone:p.text.trim(),password:pw.text);if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const Home()),(_)=>false);}catch(e){if(mounted)toast(context,'فشل الدخول: ${clean(e)}');}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(children:[const Icon(Icons.work,size:75,color:Colors.green),const Text('أرواح تخدم | مشاريع 🇩🇿',style:TextStyle(fontSize:27,fontWeight:FontWeight.bold)),const SizedBox(height:25),TextField(controller:p,keyboardType:TextInputType.phone,decoration:deco('رقم الهاتف')),const SizedBox(height:10),TextField(controller:pw,obscureText:true,decoration:deco('كلمة المرور')),const SizedBox(height:15),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:go,child:Text(busy?'جارٍ الدخول...':'دخول'))),TextButton(onPressed:()=>toast(c,'استرجاع كلمة المرور يتطلب تفعيل مزود SMS في Supabase.'),child:const Text('نسيت كلمة المرور؟')),OutlinedButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Register())),child:const Text('إنشاء حساب جديد'))]))));}
}

class Register extends StatefulWidget{const Register({super.key});@override State<Register> createState()=>_RegisterState();}
class _RegisterState extends State<Register>{final p=TextEditingController(),pw=TextEditingController(),name=TextEditingController();String role=roles.first;bool busy=false;Future<void> go()async{if(p.text.trim().isEmpty||pw.text.length<6)return toast(context,'الهاتف مطلوب وكلمة المرور 6 أحرف على الأقل');setState(()=>busy=true);try{await db.auth.signUp(phone:p.text.trim(),password:pw.text,data:{'full_name':name.text.trim(),'account_type':roleDb(role)});if(mounted)Navigator.push(c,MaterialPageRoute(builder:(_)=>Verify(phone:p.text.trim(),name:name.text.trim(),role:role)));}catch(e){toast(context,'فشل التسجيل: ${clean(e)}');}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إنشاء حساب')),body:ListView(padding:const EdgeInsets.all(20),children:[TextField(controller:name,decoration:deco('الاسم (اختياري)')),const SizedBox(height:10),TextField(controller:p,keyboardType:TextInputType.phone,decoration:deco('رقم الهاتف')),const SizedBox(height:10),TextField(controller:pw,obscureText:true,decoration:deco('كلمة المرور')),const SizedBox(height:10),dd('نوع الحساب',role,roles,(v)=>setState(()=>role=v!)),FilledButton(onPressed:busy?null:go,child:Text(busy?'جارٍ التسجيل...':'متابعة والتحقق'))]));}
}
class Verify extends StatefulWidget{final String phone,name,role;const Verify({super.key,required this.phone,required this.name,required this.role});@override State<Verify> createState()=>_VerifyState();}
class _VerifyState extends State<Verify>{final code=TextEditingController();Future<void> go()async{try{await db.auth.verifyOTP(phone:widget.phone,token:code.text.trim(),type:OtpType.sms);final u=db.auth.currentUser;if(u!=null)await db.from('profiles').upsert({'id':u.id,'full_name':widget.name,'phone':widget.phone,'account_type':roleDb(widget.role),'onboarding_completed':true,'verified':true});if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const Home()),(_)=>false);}catch(e){toast(context,'فشل التحقق: ${clean(e)}');}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('رمز التحقق')),body:Padding(padding:const EdgeInsets.all(20),child:Column(children:[const Text('أدخل رمز SMS المرسل إلى هاتفك'),const SizedBox(height:15),TextField(controller:code,keyboardType:TextInputType.number,textAlign:TextAlign.center,decoration:deco('رمز التحقق')),const SizedBox(height:15),FilledButton(onPressed:go,child:const Text('تأكيد الحساب'))])));}}

class Home extends StatelessWidget{const Home({super.key});@override Widget build(BuildContext c){final items=[['أبحث عن عمل',Icons.search,const SearchJobs()],['أبحث عن عامل',Icons.person_search,const SearchWorkers()],['الشركات تبحث عن عمال',Icons.business,const CompanyJobs()],['أبحث عن مشروع',Icons.construction,const Projects()],['أبحث عن مستثمر',Icons.attach_money,const Investors()],['الدعوات',Icons.mail,const Invitations()],['المحادثات',Icons.chat,const Chats()],['الإشعارات',Icons.notifications,const Notifications()],['حسابي',Icons.account_circle,const Profile()]];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('أرواح تخدم | مشاريع 🇩🇿'),actions:[IconButton(onPressed:()async{await db.auth.signOut();if(c.mounted)Navigator.pushAndRemoveUntil(c,MaterialPageRoute(builder:(_)=>const Login()),(_)=>false);},icon:const Icon(Icons.logout))]),body:GridView.builder(padding:const EdgeInsets.all(14),itemCount:items.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10),itemBuilder:(_,i)=>Card(child:InkWell(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>(items[i][2] as Widget))),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(items[i][1] as IconData,size:42,color:Colors.green),const SizedBox(height:8),Text(items[i][0] as String,textAlign:TextAlign.center)]))));}}}

class SearchJobs extends StatelessWidget{const SearchJobs({super.key});@override Widget build(BuildContext c)=>const SearchForm(workers:false);}
class SearchWorkers extends StatelessWidget{const SearchWorkers({super.key});@override Widget build(BuildContext c)=>const SearchForm(workers:true);}
class SearchForm extends StatefulWidget{final bool workers;const SearchForm({super.key,required this.workers});@override State<SearchForm> createState()=>_SearchFormState();}
class _SearchFormState extends State<SearchForm>{final prof=TextEditingController();String w='الكل',g='الكل';int exp=0;int minAge=0,maxAge=100;Future<void> go()async{Navigator.push(context,MaterialPageRoute(builder:(_)=>Results(workers:widget.workers,profession:prof.text.trim(),wilaya:w,gender:g,minExp:exp,minAge:minAge,maxAge:maxAge)));} @override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(widget.workers?'أبحث عن عامل':'أبحث عن عمل')),body:ListView(padding:const EdgeInsets.all(18),children:[TextField(controller:prof,decoration:deco('المهنة / الوظيفة')),dd('الولاية',w,['الكل',...wilayas],(v)=>setState(()=>w=v!)),dd('الجنس',g,genders,(v)=>setState(()=>g=v!)),TextField(keyboardType:TextInputType.number,decoration:deco('الحد الأدنى لسنوات الخبرة'),onChanged:(v)=>exp=int.tryParse(v)??0),const SizedBox(height:10),TextField(keyboardType:TextInputType.number,decoration:deco('العمر الأدنى'),onChanged:(v)=>minAge=int.tryParse(v)??0),const SizedBox(height:10),TextField(keyboardType:TextInputType.number,decoration:deco('العمر الأقصى'),onChanged:(v)=>maxAge=int.tryParse(v)??100),const SizedBox(height:10),FilledButton.icon(onPressed:go,icon:const Icon(Icons.search),label:const Text('بحث'))]));}}

class Results extends StatefulWidget{final bool workers;final String profession,wilaya,gender;final int minExp,minAge,maxAge;const Results({super.key,required this.workers,required this.profession,required this.wilaya,required this.gender,required this.minExp,required this.minAge,required this.maxAge});@override State<Results> createState()=>_ResultsState();}
class _ResultsState extends State<Results>{List<Map<String,dynamic>> rows=[];bool loading=true;int? wid;Future<void> load()async{try{if(widget.wilaya!='الكل'){final x=await db.from('wilayas').select('id').eq('name_ar',widget.wilaya).maybeSingle();wid=x?['id'];}if(widget.workers){var q=db.from('job_seeker_profiles').select('id,profession_id,wilaya_id,experience_years,age,gender,phone,skills,professions(name_ar),wilayas(name_ar)');if(wid!=null)q=q.eq('wilaya_id',wid!);if(widget.gender!='الكل')q=q.eq('gender',widget.gender=='ذكر'?'male':'female');q=q.gte('experience_years',widget.minExp).gte('age',widget.minAge).lte('age',widget.maxAge);final d=await q;rows=List<Map<String,dynamic>>.from(d);}else{var q=db.from('job_offers').select('id,title,description,vacancies,experience_years,min_age,max_age,gender,profession_id,wilaya_id,professions(name_ar),wilayas(name_ar)').eq('status','published');if(wid!=null)q=q.eq('wilaya_id',wid!);if(widget.gender!='الكل')q=q.eq('gender',widget.gender=='ذكر'?'male':'female');q=q.gte('experience_years',widget.minExp);final d=await q;rows=List<Map<String,dynamic>>.from(d);}if(widget.profession.isNotEmpty)rows=rows.where((r)=>(r['professions']?['name_ar']??'').toString().contains(widget.profession)||(r['title']??'').toString().contains(widget.profession)).toList();}catch(e){if(mounted)toast(context,'خطأ: ${clean(e)}');}finally{if(mounted)setState(()=>loading=false);}}@override void initState(){super.initState();load();}Future<void> apply(String id)async{try{await db.from('job_applications').insert({'job_offer_id':id,'applicant_id':db.auth.currentUser!.id});toast(context,'تم إرسال طلب التقديم');}catch(e){toast(context,'تعذر التقديم: ${clean(e)}');}}Future<void> invite(String id,dynamic pid)async{try{await db.from('invitations').insert({'sender_id':db.auth.currentUser!.id,'receiver_id':id,'profession_id':pid,'message':'دعوة للتواصل عبر أرواح تخدم'});toast(context,'تم إرسال الدعوة');}catch(e){toast(context,'تعذر إرسال الدعوة: ${clean(e)}');}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(widget.workers?'العمال':'فرص العمل')),body:loading?const Center(child:CircularProgressIndicator()):rows.isEmpty?const Center(child:Text('لا توجد نتائج')):ListView.builder(padding:const EdgeInsets.all(12),itemCount:rows.length,itemBuilder:(_,i){final r=rows[i];final p=r['professions']?['name_ar']??'غير محدد',w=r['wilayas']?['name_ar']??'غير محدد';return Card(child:ListTile(leading:CircleAvatar(child:Icon(widget.workers?Icons.person:Icons.work)),title:Text(widget.workers?p.toString():(r['title']??p).toString()),subtitle:Text('$w\nالخبرة: ${r['experience_years']??'-'} | العمر: ${r['age']??'-'}'),isThreeLine:true,trailing:FilledButton(onPressed:()=>widget.workers?invite(r['id'].toString(),r['profession_id']):apply(r['id'].toString()),child:Text(widget.workers?'دعوة':'تقديم'))));}));}}

class CompanyJobs extends StatefulWidget{const CompanyJobs({super.key});@override State<CompanyJobs> createState()=>_CompanyJobsState();}
class _CompanyJobsState extends State<CompanyJobs>{Future<List<Map<String,dynamic>>> load()async=>List<Map<String,dynamic>>.from(await db.from('job_offers').select('id,title,vacancies,experience_years,professions(name_ar),wilayas(name_ar)').eq('status','published').order('created_at',ascending:false));@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الشركات تبحث عن عمال')),floatingActionButton:FloatingActionButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const AddJob())).then((_){setState((){});}),child:const Icon(Icons.add)),body:FutureBuilder(future:load(),builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final a=(s.data??[]) as List<Map<String,dynamic>>;if(a.isEmpty)return const Center(child:Text('لا توجد إعلانات بعد'));return ListView.builder(itemCount:a.length,itemBuilder:(_,i)=>Card(child:ListTile(title:Text(a[i]['title'].toString()),subtitle:Text('${a[i]['professions']?['name_ar']??'-'} | ${a[i]['wilayas']?['name_ar']??'-'}\nعدد العمال: ${a[i]['vacancies']}'))));}));}}
class AddJob extends StatefulWidget{const AddJob({super.key});@override State<AddJob> createState()=>_AddJobState();}
class _AddJobState extends State<AddJob>{final title=TextEditingController(),company=TextEditingController(),profession=TextEditingController(),count=TextEditingController(text:'1'),exp=TextEditingController(text:'0');String w=wilayas.first;Future<void> save()async{try{final me=db.auth.currentUser!.id;final co=await db.from('companies').insert({'owner_id':me,'name':company.text.trim().isEmpty?'شركة':company.text.trim(),'status':'published'}).select('id').single();final wp=await db.from('wilayas').select('id').eq('name_ar',w).single();final ps=await db.from('professions').select('id').ilike('name_ar',profession.text.trim()).limit(1);await db.from('job_offers').insert({'company_id':co['id'],'owner_id':me,'profession_id':ps.isEmpty?null:ps.first['id'],'title':title.text.trim(),'wilaya_id':wp['id'],'vacancies':int.tryParse(count.text)??1,'experience_years':int.tryParse(exp.text),'status':'published'});if(mounted){toast(context,'تم نشر الإعلان');Navigator.pop(context);}}catch(e){toast(context,'تعذر النشر: ${clean(e)}');}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إعلان توظيف')),body:ListView(padding:const EdgeInsets.all(18),children:[TextField(controller:company,decoration:deco('اسم الشركة')),const SizedBox(height:10),TextField(controller:title,decoration:deco('عنوان الوظيفة')),const SizedBox(height:10),TextField(controller:profession,decoration:deco('المهنة')),const SizedBox(height:10),dd('الولاية',w,wilayas,(v)=>setState(()=>w=v!)),TextField(controller:count,keyboardType:TextInputType.number,decoration:deco('عدد العمال')),const SizedBox(height:10),TextField(controller:exp,keyboardType:TextInputType.number,decoration:deco('سنوات الخبرة')),const SizedBox(height:10),FilledButton(onPressed:save,child:const Text('نشر الإعلان'))]));}}

class Projects extends StatefulWidget{const Projects({super.key});@override State<Projects> createState()=>_ProjectsState();}
class _ProjectsState extends State<Projects>{Future<List<Map<String,dynamic>>> load()async=>List<Map<String,dynamic>>.from(await db.from('projects').select('*').eq('status','published').order('created_at',ascending:false));@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('المشاريع')),floatingActionButton:FloatingActionButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const AddProject())).then((_){setState((){});}),child:const Icon(Icons.add)),body:FutureBuilder(future:load(),builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final a=(s.data??[]) as List<Map<String,dynamic>>;if(a.isEmpty)return const Center(child:Text('لا توجد مشاريع منشورة'));return ListView.builder(itemCount:a.length,itemBuilder:(_,i)=>Card(child:ListTile(title:Text(a[i]['title'].toString()),subtitle:Text('${a[i]['category']??'-'} | ${a[i]['city']??'-'}\nرأس المال: ${a[i]['capital_required']??'-'}'))));}));}}
class AddProject extends StatefulWidget{const AddProject({super.key});@override State<AddProject> createState()=>_AddProjectState();}
class _AddProjectState extends State<AddProject>{final title=TextEditingController(),desc=TextEditingController(),capital=TextEditingController(),phone=TextEditingController();String cat=categories.first,w=wilayas.first,type=requests.first;Future<void> save()async{try{await db.from('projects').insert({'owner_id':db.auth.currentUser!.id,'title':title.text.trim(),'description':desc.text.trim(),'city':w,'category':cat,'project_type':type,'capital_required':double.tryParse(capital.text),'phone':phone.text.trim(),'status':'published'});if(mounted){toast(context,'تم نشر المشروع');Navigator.pop(context);}}catch(e){toast(context,'تعذر نشر المشروع: ${clean(e)}');}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إضافة مشروع')),body:ListView(padding:const EdgeInsets.all(18),children:[TextField(controller:title,decoration:deco('اسم المشروع')),const SizedBox(height:10),dd('نوع النشاط',cat,categories,(v)=>setState(()=>cat=v!)),dd('نوع الطلب',type,requests,(v)=>setState(()=>type=v!)),dd('الولاية',w,wilayas,(v)=>setState(()=>w=v!)),TextField(controller:capital,keyboardType:TextInputType.number,decoration:deco('قيمة المشروع')),const SizedBox(height:10),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:deco('رقم التواصل')),const SizedBox(height:10),TextField(controller:desc,maxLines:5,decoration:deco('وصف المشروع')),const SizedBox(height:10),FilledButton(onPressed:save,child:const Text('نشر المشروع'))]));}}

class Investors extends StatefulWidget{const Investors({super.key});@override State<Investors> createState()=>_InvestorsState();}
class _InvestorsState extends State<Investors>{@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('المستثمرون')),body:FutureBuilder(future:db.from('investor_profiles').select('id,display_name,investment_fields,min_amount,max_amount,wilayas(name_ar)'),builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('خطأ: ${s.error}'));final a=List<Map<String,dynamic>>.from(s.data??[]);if(a.isEmpty)return const Center(child:Text('لا يوجد مستثمرون بعد'));return ListView.builder(itemCount:a.length,itemBuilder:(_,i)=>Card(child:ListTile(leading:const Icon(Icons.attach_money),title:Text((a[i]['display_name']??'مستثمر').toString()),subtitle:Text('${a[i]['wilayas']?['name_ar']??'-'}\n${(a[i]['investment_fields']??[]).join('، ')}'))));})));}}

class Invitations extends StatefulWidget{const Invitations({super.key});@override State<Invitations> createState()=>_InvitationsState();}
class _InvitationsState extends State<Invitations>{Future<List<Map<String,dynamic>>> load()async{final id=db.auth.currentUser!.id;return List<Map<String,dynamic>>.from(await db.from('invitations').select('id,sender_id,receiver_id,status,message,professions(name_ar),created_at').or('sender_id.eq.$id,receiver_id.eq.$id').order('created_at',ascending:false));}Future<void> respond(String id,String status)async{try{await db.from('invitations').update({'status':status,'responded_at':DateTime.now().toIso8601String()}).eq('id',id);setState((){});}catch(e){toast(context,'تعذر التحديث: ${clean(e)}');}}Future<void> chat(String other)async{try{final me=db.auth.currentUser!.id;final ex=await db.from('conversation_participants').select('conversation_id').eq('user_id',me);String? cid;for(final r in List<Map<String,dynamic>>.from(ex)){final id=r['conversation_id'].toString();final q=await db.from('conversation_participants').select('user_id').eq('conversation_id',id).eq('user_id',other);if(q.isNotEmpty){cid=id;break;}}if(cid==null){final c=await db.from('conversations').insert({}).select('id').single();cid=c['id'].toString();await db.from('conversation_participants').insert([{'conversation_id':cid,'user_id':me},{'conversation_id':cid,'user_id':other}]);}if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>Chat(cid!)));}catch(e){toast(context,'تعذر فتح المحادثة: ${clean(e)}');}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الدعوات')),body:FutureBuilder(future:load(),builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final a=List<Map<String,dynamic>>.from(s.data??[]);final me=db.auth.currentUser!.id;if(a.isEmpty)return const Center(child:Text('لا توجد دعوات'));return ListView.builder(itemCount:a.length,itemBuilder:(_,i){final r=a[i];final incoming=r['receiver_id']==me;return Card(child:ListTile(title:Text(incoming?'دعوة واردة':'دعوة مرسلة'),subtitle:Text('${r['professions']?['name_ar']??'تواصل'}\nالحالة: ${r['status']}'),trailing:incoming&&r['status']=='pending'?Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:()=>respond(r['id'].toString(),'accepted'),icon:const Icon(Icons.check,color:Colors.green)),IconButton(onPressed:()=>respond(r['id'].toString(),'rejected'),icon:const Icon(Icons.close,color:Colors.red))]):r['status']=='accepted'?IconButton(onPressed:()=>chat(incoming?r['sender_id'].toString():r['receiver_id'].toString()),icon:const Icon(Icons.chat)):null));});})));}}

class Chats extends StatelessWidget{const Chats({super.key});@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('المحادثات')),body:FutureBuilder(future:db.from('conversation_participants').select('conversation_id').eq('user_id',db.auth.currentUser!.id),builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final a=List<Map<String,dynamic>>.from(s.data??[]);if(a.isEmpty)return const Center(child:Text('لا توجد محادثات'));return ListView.builder(itemCount:a.length,itemBuilder:(_,i)=>ListTile(leading:const Icon(Icons.chat),title:Text('محادثة ${i+1}'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Chat(a[i]['conversation_id'].toString())))));})));}}
class Chat extends StatefulWidget{final String id;const Chat(this.id,{super.key});@override State<Chat> createState()=>_ChatState();}
class _ChatState extends State<Chat>{final t=TextEditingController();Future<List<Map<String,dynamic>>> load()async=>List<Map<String,dynamic>>.from(await db.from('messages').select('*').eq('conversation_id',widget.id).order('created_at'));Future<void> send()async{if(t.text.trim().isEmpty)return;try{await db.from('messages').insert({'conversation_id':widget.id,'sender_id':db.auth.currentUser!.id,'body':t.text.trim()});t.clear();setState((){});}catch(e){toast(context,'تعذر الإرسال: ${clean(e)}');}}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('المحادثة')),body:Column(children:[Expanded(child:FutureBuilder(future:load(),builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final a=List<Map<String,dynamic>>.from(s.data??[]);return ListView.builder(itemCount:a.length,itemBuilder:(_,i)=>ListTile(title:Text(a[i]['body'].toString())));})),Row(children:[Expanded(child:TextField(controller:t,decoration:deco('اكتب رسالة'))),IconButton(onPressed:send,icon:const Icon(Icons.send))])]));}}

class Notifications extends StatelessWidget{const Notifications({super.key});@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الإشعارات')),body:FutureBuilder(future:db.from('notifications').select('*').eq('user_id',db.auth.currentUser!.id).order('created_at',ascending:false),builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final a=List<Map<String,dynamic>>.from(s.data??[]);if(a.isEmpty)return const Center(child:Text('لا توجد إشعارات'));return ListView.builder(itemCount:a.length,itemBuilder:(_,i)=>ListTile(leading:const Icon(Icons.notifications),title:Text((a[i]['title']??'').toString()),subtitle:Text((a[i]['body']??'').toString())));})));}}
class Profile extends StatefulWidget{const Profile({super.key});@override State<Profile> createState()=>_ProfileState();}
class _ProfileState extends State<Profile>{final name=TextEditingController();String role='job_seeker';bool loading=true;@override void initState(){super.initState();load();}Future<void> load()async{final r=await db.from('profiles').select('*').eq('id',db.auth.currentUser!.id).maybeSingle();if(r!=null){name.text=(r['full_name']??'').toString();role=(r['account_type']??'job_seeker').toString();}if(mounted)setState(()=>loading=false);}Future<void> save()async{try{await db.from('profiles').update({'full_name':name.text.trim(),'updated_at':DateTime.now().toIso8601String()}).eq('id',db.auth.currentUser!.id);toast(context,'تم الحفظ');}catch(e){toast(context,'تعذر الحفظ: ${clean(e)}');}}String ar(String x)=>x=='job_seeker'?'باحث عن عمل':x=='investor'?'مستثمر':x=='project_owner'?'صاحب مشروع':'صاحب عمل / شركة';@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('حسابي')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(18),children:[const CircleAvatar(radius:45,child:Icon(Icons.person,size:50)),const SizedBox(height:20),TextField(controller:name,decoration:deco('الاسم')),ListTile(leading:const Icon(Icons.badge),title:const Text('نوع الحساب'),subtitle:Text(ar(role))),FilledButton(onPressed:save,child:const Text('حفظ'))])));}}
